#include "KeyboardTranslator_win32.hpp"

#include <Windows.h>

namespace phantom::core
{
	std::map<const uint, KeyboardKey> KeyboardTranslator_win32::database_
	{
		{ VK_NONAME, KeyboardKey::KEY_NO_CODE },

	{ 0x41, KeyboardKey::KEY_A },
	{ 0x42, KeyboardKey::KEY_B },
	{ 0x43, KeyboardKey::KEY_C },
	{ 0x44, KeyboardKey::KEY_D },
	{ 0x45, KeyboardKey::KEY_E },
	{ 0x46, KeyboardKey::KEY_F },
	{ 0x47, KeyboardKey::KEY_G },
	{ 0x48, KeyboardKey::KEY_H },
	{ 0x49, KeyboardKey::KEY_I },
	{ 0x4A, KeyboardKey::KEY_J },
	{ 0x4B, KeyboardKey::KEY_K },
	{ 0x4C, KeyboardKey::KEY_L },
	{ 0x4D, KeyboardKey::KEY_M },
	{ 0x4E, KeyboardKey::KEY_N },
	{ 0x4F, KeyboardKey::KEY_O },
	{ 0x50, KeyboardKey::KEY_P },
	{ 0x51, KeyboardKey::KEY_Q },
	{ 0x52, KeyboardKey::KEY_R },
	{ 0x53, KeyboardKey::KEY_S },
	{ 0x54, KeyboardKey::KEY_T },
	{ 0x55, KeyboardKey::KEY_U },
	{ 0x56, KeyboardKey::KEY_V },
	{ 0x57, KeyboardKey::KEY_W },
	{ 0x58, KeyboardKey::KEY_X },
	{ 0x59, KeyboardKey::KEY_Y },
	{ 0x5A, KeyboardKey::KEY_Z },

	{ 0x30, KeyboardKey::KEY_0 },
	{ 0x31, KeyboardKey::KEY_1 },
	{ 0x32, KeyboardKey::KEY_2 },
	{ 0x33, KeyboardKey::KEY_3 },
	{ 0x34, KeyboardKey::KEY_4 },
	{ 0x35, KeyboardKey::KEY_5 },
	{ 0x36, KeyboardKey::KEY_6 },
	{ 0x37, KeyboardKey::KEY_7 },
	{ 0x38, KeyboardKey::KEY_8 },
	{ 0x39, KeyboardKey::KEY_9 },

	{ VK_F1, KeyboardKey::KEY_F1 },
	{ VK_F2, KeyboardKey::KEY_F2 },
	{ VK_F3, KeyboardKey::KEY_F3 },
	{ VK_F4, KeyboardKey::KEY_F4 },
	{ VK_F5, KeyboardKey::KEY_F5 },
	{ VK_F6, KeyboardKey::KEY_F6 },
	{ VK_F7, KeyboardKey::KEY_F7 },
	{ VK_F8, KeyboardKey::KEY_F8 },
	{ VK_F9, KeyboardKey::KEY_F9 },
	{ VK_F10, KeyboardKey::KEY_F10 },
	{ VK_F11, KeyboardKey::KEY_F11 },
	{ VK_F12, KeyboardKey::KEY_F12 },
	{ VK_F13, KeyboardKey::KEY_F13 },
	{ VK_F14, KeyboardKey::KEY_F14 },
	{ VK_F15, KeyboardKey::KEY_F15 },
	{ VK_F16, KeyboardKey::KEY_F16 },
	{ VK_F17, KeyboardKey::KEY_F17 },
	{ VK_F18, KeyboardKey::KEY_F18 },
	{ VK_F19, KeyboardKey::KEY_F19 },
	{ VK_F20, KeyboardKey::KEY_F20 },
	{ VK_F21, KeyboardKey::KEY_F21 },
	{ VK_F22, KeyboardKey::KEY_F22 },
	{ VK_F23, KeyboardKey::KEY_F23 },
	{ VK_F24, KeyboardKey::KEY_F24 },

	{ VK_NUMPAD0, KeyboardKey::KEY_NUM0 },
	{ VK_NUMPAD1, KeyboardKey::KEY_NUM1 },
	{ VK_NUMPAD2, KeyboardKey::KEY_NUM2 },
	{ VK_NUMPAD3, KeyboardKey::KEY_NUM3 },
	{ VK_NUMPAD4, KeyboardKey::KEY_NUM4 },
	{ VK_NUMPAD5, KeyboardKey::KEY_NUM5 },
	{ VK_NUMPAD6, KeyboardKey::KEY_NUM6 },
	{ VK_NUMPAD7, KeyboardKey::KEY_NUM7 },
	{ VK_NUMPAD8, KeyboardKey::KEY_NUM8 },
	{ VK_NUMPAD9, KeyboardKey::KEY_NUM9 },

	{ VK_MULTIPLY, KeyboardKey::KEY_NUMMULTIPLY },
	{ VK_DIVIDE, KeyboardKey::KEY_NUMDIVIDE },
	{ VK_ADD, KeyboardKey::KEY_NUMADD },
	{ VK_SUBTRACT, KeyboardKey::KEY_NUMSUBTRACT },

	{ VK_BACK, KeyboardKey::KEY_BACKSPACE },
	{ VK_TAB, KeyboardKey::KEY_TAB },
	{ VK_SPACE, KeyboardKey::KEY_SPACE },
	{ VK_RETURN, KeyboardKey::KEY_ENTER },
	{ VK_CLEAR, KeyboardKey::KEY_CLEAR },
	{ VK_PAUSE, KeyboardKey::KEY_PAUSE },
	{ VK_ESCAPE, KeyboardKey::KEY_ESCAPE },

	{ VK_PRIOR, KeyboardKey::KEY_PAGEUP },
	{ VK_NEXT, KeyboardKey::KEY_PAGEDOWN },
	{ VK_END, KeyboardKey::KEY_END },
	{ VK_HOME, KeyboardKey::KEY_HOME },
	{ VK_INSERT, KeyboardKey::KEY_INSERT },
	{ VK_DELETE, KeyboardKey::KEY_DELETE },
	{ VK_MULTIPLY, KeyboardKey::KEY_MULTIPLY },
	{ VK_DIVIDE, KeyboardKey::KEY_DIVIDE },
	{ VK_ADD, KeyboardKey::KEY_ADD },
	{ VK_SUBTRACT, KeyboardKey::KEY_SUBTRACT },
	{ VK_SEPARATOR, KeyboardKey::KEY_SEPARATOR },
	{ VK_DECIMAL, KeyboardKey::KEY_DECIMAL },

	{ VK_UP, KeyboardKey::KEY_UP },
	{ VK_DOWN, KeyboardKey::KEY_DOWN },
	{ VK_LEFT, KeyboardKey::KEY_LEFT },
	{ VK_RIGHT, KeyboardKey::KEY_RIGHT },

	{ VK_SELECT, KeyboardKey::KEY_SELECT },
	{ VK_PRINT, KeyboardKey::KEY_PRINTSCREEN },
	{ VK_EXECUTE, KeyboardKey::KEY_EXE },
	{ VK_SNAPSHOT, KeyboardKey::KEY_SNAPSHOT },
	{ VK_HELP, KeyboardKey::KEY_HELP },
	{ VK_SLEEP, KeyboardKey::KEY_SLEEP },

	{ VK_SCROLL, KeyboardKey::KEY_SCROLLLOCK },
	{ VK_CAPITAL, KeyboardKey::KEY_CAPSLOCK },

	{ VK_OEM_NEC_EQUAL, KeyboardKey::KEY_OEM_NUMEQUAL },
	{ VK_OEM_FJ_JISHO, KeyboardKey::KEY_OEM_DICTIONARY },
	{ VK_OEM_FJ_MASSHOU, KeyboardKey::KEY_OEM_UNREGISTER },
	{ VK_OEM_FJ_TOUROKU, KeyboardKey::KEY_OEM_REGISTER },
	{ VK_OEM_FJ_LOYA, KeyboardKey::KEY_OEM_LOYAYUBI },
	{ VK_OEM_FJ_ROYA, KeyboardKey::KEY_OEM_ROYAYUBI },
	{ VK_OEM_PLUS, KeyboardKey::KEY_OEM_PLUS },
	{ VK_OEM_COMMA, KeyboardKey::KEY_OEM_COMMA },
	{ VK_OEM_MINUS, KeyboardKey::KEY_OEM_MINUS },
	{ VK_OEM_PERIOD, KeyboardKey::KEY_OEM_PERIOD },
	{ VK_OEM_1, KeyboardKey::KEY_OEM1 },
	{ VK_OEM_2, KeyboardKey::KEY_OEM2 },
	{ VK_OEM_3, KeyboardKey::KEY_OEM3 },
	{ VK_OEM_4, KeyboardKey::KEY_OEM4 },
	{ VK_OEM_5, KeyboardKey::KEY_OEM5 },
	{ VK_OEM_6, KeyboardKey::KEY_OEM6 },
	{ VK_OEM_7, KeyboardKey::KEY_OEM7 },
	{ VK_OEM_8, KeyboardKey::KEY_OEM8 },
	{ VK_OEM_AX, KeyboardKey::KEY_OEM_AX },
	{ VK_OEM_102, KeyboardKey::KEY_OEM102 },

	{ VK_BROWSER_BACK, KeyboardKey::KEY_BROWSER_BACK },
	{ VK_BROWSER_FORWARD, KeyboardKey::KEY_BROWSER_FORWARD },
	{ VK_BROWSER_REFRESH, KeyboardKey::KEY_BROWSER_REFRESH },
	{ VK_BROWSER_STOP, KeyboardKey::KEY_BROWSER_STOP },
	{ VK_BROWSER_SEARCH, KeyboardKey::KEY_BROWSER_SEARCH },
	{ VK_BROWSER_FAVORITES, KeyboardKey::KEY_BROWSER_FAVORITE },
	{ VK_BROWSER_HOME, KeyboardKey::KEY_BROWSER_HOME },

	{ VK_VOLUME_UP, KeyboardKey::KEY_VOLUME_UP },
	{ VK_VOLUME_DOWN, KeyboardKey::KEY_VOLUME_DOWN },
	{ VK_VOLUME_MUTE, KeyboardKey::KEY_VOLUME_MUTE },

	{ VK_MEDIA_NEXT_TRACK, KeyboardKey::KEY_MEDIA_NEXT },
	{ VK_MEDIA_PREV_TRACK, KeyboardKey::KEY_MEDIA_PREV },
	{ VK_MEDIA_STOP, KeyboardKey::KEY_MEDIA_STOP },
	{ VK_MEDIA_PLAY_PAUSE, KeyboardKey::KEY_MEDIA_PLAY_PAUSE },
	{ VK_LAUNCH_MEDIA_SELECT, KeyboardKey::KEY_MEDIA_SELECT },

	{ VK_LAUNCH_APP1,  KeyboardKey::KEY_LAUNCH_APP1 },
	{ VK_LAUNCH_APP2, KeyboardKey::KEY_LAUNCH_APP2 },
	{ VK_LAUNCH_MAIL, KeyboardKey::KEY_LAUNCH_MAIL },

	{ VK_APPS, KeyboardKey::KEY_APPLICATION },

	{ VK_RSHIFT, KeyboardKey::KEY_RSHIFT },
	{ VK_RMENU, KeyboardKey::KEY_RALT },
	{ VK_RCONTROL, KeyboardKey::KEY_RCTRL },
	{ VK_RWIN, KeyboardKey::KEY_RWIN },
	{ VK_LSHIFT, KeyboardKey::KEY_LSHIFT },
	{ VK_LMENU, KeyboardKey::KEY_LALT },
	{ VK_LWIN, KeyboardKey::KEY_LWIN },

	{ VK_SHIFT, KeyboardKey::KEY_SHIFT },
	{ VK_MENU, KeyboardKey::KEY_ALT },
	{ VK_CONTROL, KeyboardKey::KEY_CTRL },
	};

	KeyboardKey KeyboardTranslator_win32::translate(const uint key) noexcept
	{
		return database_[key];
	}
}